labelme/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'', include('social_django.urls', namespace='social')),
    url(r'^$', RedirectView.as_view(pattern_name="orders:list"))
]

urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url

from orders.views import OrdersList, OrdersDetails, OrderUpload, OrderLabel

urlpatterns = [
    url(r"^$", OrdersList.as_view(), name="list"),
    url(r"^(?P<pk>[\d]+)/$", OrdersDetails.as_view(), name="details"),
    url(r"^new/$", OrderUpload.as_view(), name="new"),
    url(r"^label/$", OrderLabel.as_view(), name="label")
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from users.views import LoginView

urlpatterns = [
    url(r"^login/$", LoginView.as_view(), name="login"),
    url(r"^logout/$", LogoutView.as_view(next_page="/"), name="logout")
]

orders/models.py
from django.conf import settings
from django.db import models

from users.models import CustomUser


class Order(models.Model):
    issuer = models.ForeignKey(settings.AUTH_USER_MODEL)
    date_issued = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=32)
    verifications_needed = models.PositiveIntegerField(default=2, verbose_name="Same answers to accept")
    price = models.DecimalField(max_digits=10, decimal_places=5, default=0)
    description = models.TextField()
    currency = models.CharField(max_length=16, choices=(
        ('bitcoin', 'BITCOIN'),
        ('litecoin', 'LITECOIN'),
        ('etherum', 'ETHEREUM')
    ))
    is_done = models.BooleanField(default=False)

    class Meta:
        ordering = ['is_done']

    def charge(self):
        admin = CustomUser.objects.get(is_superuser=True)
        response = self.issuer.transfer_money(admin.email, self.price, self.currency)
        return response['status'] == 'completed'


class Record(models.Model):
    RECORD_CHOICES = (
        ('image', 'Image'),
        ('text', 'Text'),
    )
    order = models.ForeignKey('Order')
    type = models.CharField(max_length=16, choices=RECORD_CHOICES)
    asset = models.TextField()
    is_done = models.BooleanField(default=False)
    labeled_as = models.TextField()

    class Meta:
        ordering = ['is_done']

    def check_if_done(self, answer):
        if self.label_set.filter(answer__iexact=answer).count() >= self.order.verifications_needed:
            self.labeled_as = answer
            self.is_done = True
            self.save()


class Label(models.Model):
    record = models.ForeignKey('Record')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    answer = models.TextField(verbose_name="Your answer")

orders/forms.py
from django import forms

from orders.models import Record, Order, Label


class OrderForm(forms.ModelForm):
    zip_file = forms.FileField()

    class Meta:
        model = Order
        fields = ('name', 'verifications_needed', 'description', 'zip_file')


class LabelForm(forms.ModelForm):

    class Meta:
        model = Label
        fields = ('answer', 'record')
        widgets = {
            'record': forms.HiddenInput,
            'answer': forms.TextInput
        }

orders/views.py
import os
import zipfile
from uuid import uuid4

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.functional import cached_property
from django.views.generic import ListView, DetailView, CreateView

from orders.forms import OrderForm, LabelForm
from orders.models import Order, Label, Record


@method_decorator(login_required, name="dispatch")
class OrdersList(ListView):
    template_name = "orders/list.html"

    def get_queryset(self):
        qs = self.request.user.order_set.all().prefetch_related('record_set')
        qs = qs.annotate(records_total=Count('record'))
        qs = qs.annotate(records_done=Sum('record__is_done'))
        return qs


@method_decorator(login_required, name="dispatch")
class OrdersDetails(DetailView):
    template_name = "orders/details.html"

    def get_queryset(self):
        # noinspection PyCallByClass
        return OrdersList.get_queryset(self)


@method_decorator(login_required, name="dispatch")
class OrderUpload(CreateView):
    model = Order
    form_class = OrderForm
    template_name = "orders/upload.html"
    price_per_item = settings.PRICE_PER_ITEM
    currency = settings.COINBASE_CURRENCY

    def get_success_url(self):
        return reverse("orders:list")

    def form_valid(self, form):
        order = form.save(commit=False)
        order.issuer = self.request.user
        order.save()
        files_count = self.extract_zipfile(form.cleaned_data["zip_file"], order)
        order.price = files_count * order.verifications_needed * settings.PRICE_PER_ITEM
        order.currency = settings.COINBASE_CURRENCY
        order.save()
        # order.charge()
        return HttpResponseRedirect(self.get_success_url())

    def extract_zipfile(self, archive, order):
        counter = 0
        unzipped = zipfile.ZipFile(archive)
        for old_filename in unzipped.namelist():
            _, ext = os.path.splitext(old_filename)
            new_filename = f"{uuid4().hex}{ext}"
            path = os.path.join(settings.MEDIA_ROOT, "storage", new_filename)
            asset_path = os.path.join(settings.MEDIA_URL, "storage", new_filename)

            with open(path, "wb") as f:
                f.write(unzipped.read(old_filename))

            order.record_set.create(asset=asset_path, type="image")
            counter += 1
        return counter


@method_decorator(login_required, name="dispatch")
class OrderLabel(CreateView):
    model = Label
    form_class = LabelForm
    template_name = "orders/label.html"

    @cached_property
    def record(self):
        qs = Record.objects.filter(is_done=False).exclude(label__user=self.request.user)# .exclude(order__issuer=self.request.user)
        if "record" in self.request.POST:
            return qs.filter(pk=self.request.POST.get("record"))
        else:
            return qs.order_by('?').first()

    def get_initial(self):
        return {
            "record": self.record
        }

    def get_context_data(self, **kwargs):
        kwargs['record'] = self.record
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse("orders:label")

    def form_valid(self, form):
        label = form.save(commit=False)
        label.user = self.request.user
        label.save()
        label.record.check_if_done(label.answer)
        if label.user.check_if_payment():
            label.user.pay(settings.REWARD_AFTER * settings.REWARD_PER_ITEM, settings.COINBASE_CURRENCY)
        return HttpResponseRedirect(self.get_success_url())

orders/templates/orders/details.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ order.name }}</h1>
    <p>Order cost: {{ order.price }} {{ order.currency }}</p>
    {% for record in order.record_set.all %}
        {% if record.type == 'image' %}
            <img src="{{ record.asset }}" style="max-width: 200px; max-height: 200px;">
            {% if record.is_done %}
                {{ record.labeled_as }}
            {% else %}
                No data available yet
            {% endif %}
        {% elif record.type == 'text' %}
            <p> {{ record.asset }}</p>
            {% if record.is_done %}
                {{ record.labeled_as }}
            {% else %}
                No data available yet
            {% endif %}
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

orders/templates/orders/label.html
{% extends "base.html" %}{% load bootstrap3 %}


{% block content %}
    {% if not record %}
        <h3>No data to label. Please come back soon.</h3>
    {% else %}
        <div class="text-center col-sm-offset-4 col-sm-4">
            {% if record.type == 'image' %}
                <img src="{{ record.asset }}" style="max-width: 400px; max-height: 400px;">
            {% elif record.type == 'text' %}
                <div class="text-resource">{{record.asset}}</div>
            {% else %}
                Error occured
            {% endif %}
            <div class="hr-line-dashed"></div>
            <p>{{ record.order.description }}</p>
            <div class="hr-line-dashed"></div>
            <form method="post" action="">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary" type="submit"><i class="fa fa-tag"></i>&nbsp;Save</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

orders/templates/orders/list.html
{% extends "base.html" %}

{% block content %}
    {% regroup object_list by is_done as orders_groups %}
    {% for group in orders_groups %}
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                {% if not group.grouper %}
                    <h5>In progress</h5>
                {% else %}
                    <h5>Done</h5>
                {% endif %}
            </div>
            <div class="ibox-content">
                <div class="row">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Dataset size</th>
                            <th>Charged for</th>
                            <th>Finished</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in group.list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url "orders:details" pk=order.pk %}">{{ order.name }}</a></td>
                                <td>{{ order.record_set.count }}</td>
                                <td>{{ order.price }} ETH</td>
                                <td>{% widthratio order.records_done order.records_total 100 %}%</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endfor %}

    <hr>
    <a href="{% url "orders:new" %}" class="btn btn-primary" type="button"><i class="fa fa-plus"></i>&nbsp;Add new</a>
{% endblock %}

orders/templates/orders/upload.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <h1>Create new order</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="hr-line-dashed"></div>
        <p>Price per item: <strong>{{ view.price_per_item }} {{ view.currency }}</strong></p>
        <div class="hr-line-dashed"></div>
        <button class="btn btn-primary" type="submit"><i class="fa fa-check"></i>&nbsp;Submit</button>
    </form>
{% endblock %}